# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('FoS_DeckPro', 'FoS_DeckPro'),
        ('requirements.txt', '.'),
        ('README.md', '.'),
        ('CHANGELOG.json', '.'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtNetwork',
        'requests',
        'json',
        'csv',
        'os',
        'sys',
        'pathlib',
        'logging',
        'datetime',
        'urllib.parse',
        'urllib.request',
        'ssl',
        'threading',
        'queue',
        'sqlite3',
        'xml.etree.ElementTree',
        'xml.dom.minidom',
        'zipfile',
        'tempfile',
        'shutil',
        'subprocess',
        'platform',
        'ctypes',
        'weakref',
        'functools',
        'collections',
        'itertools',
        'operator',
        're',
        'math',
        'statistics',
        'hashlib',
        'base64',
        'pickle',
        'shelve',
        'configparser',
        'argparse',
        'getpass',
        'time',
        'calendar',
        'locale',
        'codecs',
        'io',
        'abc',
        'enum',
        'typing',
        'dataclasses',
        'contextlib',
        'copy',
        'pprint',
        'traceback',
        'warnings',
        'builtins',
        'types',
        'inspect',
        'ast',
        'dis',
        'marshal',
        'imp',
        'importlib',
        'pkgutil',
        'pkg_resources',
        'setuptools',
        'distutils',
        'ensurepip',
        'venv',
        'virtualenv',
        'pip',
        'wheel',
        'setuptools',
        'distutils',
        'ensurepip',
        'venv',
        'virtualenv',
        'pip',
        'wheel',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FoS-DeckPro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
