site_name: ManaBox Enhancer Documentation
nav:
  - Home: index.md
  - Getting Started: ../../FoS_DeckPro/docs/GETTING_STARTED.md
  - Architecture: ../../FoS_DeckPro/docs/architecture.md
  - UI Style Guide: ../../FoS_DeckPro/docs/ui-style-guide.md
  - Roadmap: ../../FoS_DeckPro/docs/ROADMAP.md
  - Tutorials:
      - Overview: ../../FoS_DeckPro/docs/TUTORIALS.md
      - Building First Break: ../../FoS_DeckPro/docs/tutorial_building_first_break.md
      - Processing Packing Slip: ../../FoS_DeckPro/docs/tutorial_processing_packing_slip.md
      - Undo Removal: ../../FoS_DeckPro/docs/tutorial_undo_removal.md
  - Project Infrastructure:
      - CI/CD Workflows: docs/ci-cd.md
