# Card field definitions and helpers migrated from the monolithic app

CARD_FIELDS = [
    "Altered",
    "cardhoarder_url",
    "cardmarket_url",
    "cmc",
    "Collector number",
    "color_identity",
    "colors",
    "Condition",
    "eur",
    "eur_etched",
    "eur_foil",
    "Foil",
    "image_url",
    "Language",
    "legal_commander",
    "legal_pauper",
    "ManaBox ID",
    "mana_cost",
    "Misprint",
    "Name",
    "oracle_text",
    "Purchase price",
    "Purchase price currency",
    "Quantity",
    "Rarity",
    "Scryfall ID",
    "Set code",
    "Set name",
    "tcgplayer_url",
    "tix",
    "type_line",
    "usd",
    "usd_etched",
    "usd_foil",
    "Whatnot price"
]

# Optionally, a Card class could be implemented if needed by the modular app.
