name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1 xvfb
          
      - name: Build executable (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile --windowed --name FoS-DeckPro --icon=icon.icns main.py
          cd dist && zip -r FoS-DeckPro.app.zip FoS-DeckPro.app && cd ..

      - name: Build executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --windowed --name FoS-DeckPro --icon=icon.ico main.py

      - name: Build executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --windowed --name FoS-DeckPro --icon=icon.png main.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ManaBox_Enhancer-${{ matrix.os }}
          path: dist/ManaBox_Enhancer*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/ManaBox_Enhancer-ubuntu-latest/*
            artifacts/ManaBox_Enhancer-windows-latest/*
            artifacts/ManaBox_Enhancer-macos-latest/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 