name: Build and Release FoS-DeckPro

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest ManaBox_Enhancer/tests FoS_DeckPro/tests --maxfail=3 --disable-warnings -v

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed FoS_DeckPro/main.py --name "FoS-DeckPro"
        # On Windows, output is dist/FoS-DeckPro.exe
        # On Mac/Linux, output is dist/FoS-DeckPro

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: FoS-DeckPro-${{ runner.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist

      - name: List artifacts
        run: ls -R dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/FoS-DeckPro*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 