name: Build Windows and Mac Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.8.0)'
        required: true
        default: 'v1.8.0'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name "FoS-DeckPro" main.py
      
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: FoS-DeckPro-Windows
          path: dist/FoS-DeckPro.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name "FoS-DeckPro" main.py
      
      - name: Upload Mac executable
        uses: actions/upload-artifact@v4
        with:
          name: FoS-DeckPro-Mac
          path: dist/FoS-DeckPro

  create-release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Set tag name
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG_NAME="${{ github.event.inputs.version }}"
          else
            TAG_NAME="${GITHUB_REF##*/}"
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      
      - name: Validate tag name
        run: |
          if [[ -z "$TAG_NAME" || "$TAG_NAME" == "main" || ! "$TAG_NAME" =~ ^v[0-9]+ ]]; then
            echo "::error::You must provide a valid version tag (e.g., v1.8.0). Current: '$TAG_NAME'"
            exit 1
          fi
      
      - name: Download Windows executable
        uses: actions/download-artifact@v4
        with:
          name: FoS-DeckPro-Windows
          path: windows
      
      - name: Download Mac executable
        uses: actions/download-artifact@v4
        with:
          name: FoS-DeckPro-Mac
          path: mac
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows/FoS-DeckPro.exe
            mac/FoS-DeckPro
          tag_name: ${{ env.TAG_NAME }}
          name: FoS DeckPro ${{ env.TAG_NAME }}
          body: |
            ## FoS DeckPro ${{ env.TAG_NAME }}
            
            ### Downloads
            - **Windows**: FoS-DeckPro.exe
            - **macOS**: FoS-DeckPro
            
            ### Installation
            1. Download the appropriate file for your operating system
            2. Make the file executable (macOS/Linux): `chmod +x FoS-DeckPro`
            3. Run the application
            
            ### Changes
            - Automated build and release system
            - Standalone executables for easy installation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
