name: Cleanup Old Releases

on:
  release:
    types: [published]

jobs:
  cleanup-old-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old releases and assets
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 