name: Public/Private Separation Enforcement

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

jobs:
  separation-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for forbidden files
        run: |
          forbidden_paths=(legacy/ LEGACY_*_ARCHIVE.md)
          for path in "${forbidden_paths[@]}"; do
            if git ls-files --error-unmatch "$path" 2>/dev/null; then
              echo "Forbidden file or directory detected: $path"
              exit 1
            fi
          done
      - name: Check for forbidden references in public files
        run: |
          grep -r --exclude-dir=legacy --exclude=LEGACY_*_ARCHIVE.md -E 'legacy/|LEGACY_.*_ARCHIVE\.md' FoS_DeckPro/ docs-site/ || true
          if grep -r --exclude-dir=legacy --exclude=LEGACY_*_ARCHIVE.md -E 'legacy/|LEGACY_.*_ARCHIVE\.md' FoS_DeckPro/ docs-site/; then
            echo "Forbidden reference to legacy content detected."
            exit 1
          fi 