name: Python Lint

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install flake8 and black
        run: |
          pip install flake8 black
      - name: Run flake8
        run: flake8 FoS_DeckPro/ --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run black (check only)
        run: black --check FoS_DeckPro/ 