name: Test Coverage

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r FoS_DeckPro/requirements.txt
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: pytest --cov=FoS_DeckPro/ --cov-fail-under=90 